name: 'auto-cancellation-running-action'
description: 'Auto Cancellation allows you to only run builds for the latest commits in the queue.'
inputs:
  github-token:
    description: The GitHub token used to create an authenticated client.
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: git-pull-request
  color: blue